name: Enhancement
description: Suggest an improvement
title: "[ENHANCEMENT]: "
labels: []

body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Request

        This enhancement is suggested under **NSoC'26 (Nexus Spring of Code)**.
        If you are contributing through another open source event such as Apertre 3.0 or GSSoC'26, mention it here as well.
        Kindly consider assigning it to me if appropriate.

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation